/**
 * 画笔、笔迹坐标、工具状态类型定义
 *
 * @author Generated by LecturePanel migration
 */

// 画笔工具类型
export type ToolType = "pointer" | "pen" | "eraser" | "highlighter";

// 画笔样式配置
export interface PenStyle {
  color: string;
  width: number;
  opacity: number;
}

// 坐标点
export interface Point {
  x: number;
  y: number;
  pressure?: number;
  timestamp?: number;
}

// 笔迹路径
export interface Stroke {
  id: string;
  tool: ToolType;
  points: Point[];
  style: PenStyle;
  timestamp: number;
  // 子母题模式：用于区分左右屏笔迹（"left" | "right"）
  // 普通题模式：此字段为 undefined，保持向后兼容
  side?: "left" | "right";
}

// 画板状态
export interface BoardState {
  currentTool: ToolType;
  penStyle: PenStyle;
  strokes: Stroke[];
  undoStack: Stroke[][];
  redoStack: Stroke[][];
}

// 工具栏配置
export interface ToolConfig {
  id: string;
  icon: string;
  label: string;
  type: ToolType;
  active: boolean;
  disabled?: boolean;
}

// 画板区域信息
export interface BoardArea {
  width: number;
  height: number;
  scrollTop: number;
  scrollLeft: number;
  scale: number;
}

// 触摸事件状态
export interface TouchState {
  isDrawing: boolean;
  currentStroke?: Stroke;
  lastPoint?: Point;
  gestureCount: number;
}

// 快照配置
export interface SnapshotConfig {
  includeOverscroll: boolean;
  format: "png" | "jpeg" | "webp";
  quality: number;
}

// 快照数据
export interface SnapshotData {
  questionId: number;
  imageUrl: string;
  strokes: Stroke[];
  timestamp: number;
  metadata: {
    boardArea: BoardArea;
    config: SnapshotConfig;
  };
}

// 工具栏位置状态
export interface ToolbarPosition {
  x: number;
  y: number;
  isCustom: boolean;
}

// 画板配置
export interface BoardConfig {
  enablePressure: boolean;
  smoothing: number;
  maxUndoSteps: number;
  autoSave: boolean;
  debugMode: boolean;
}
